version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

parameters:
  config:
    type: enum
    enum: ["", config1, config2]
    default: ""

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/<< pipeline.parameters.config >>.yml

workflows:
  setup:
    when: << pipeline.parameters.config >>
    jobs:
      - setup
