version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

parameters:
  manual:
    type: boolean
    default: false
  file:
    type: enum
    enum: [config1, config2]
    default: config1

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/<< pipeline.parameters.file >>.yml
          parameters: '{}'

workflows:
  setup:
    when: << pipeline.parameters.manual >>
    jobs:
      - setup
