version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

# 実行時に渡すパラメータ
# config1 だったら config1.yml を、config2 だったら config2.yml を使って実行する
parameters:
  config:
    type: enum
    enum: ["", config1, config2]
    default: "" # push 手動実行時以外は動かないようにしてみたかったので空文字をデフォルトにしておいた

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          # ここでパラメータを使ってる
          configuration_path: .circleci/<< pipeline.parameters.config >>.yml

  runner-test:
    machine: true
    resource_class: bufferings/hello-runner
    steps:
      - run: echo "Hi I'm on Runners!"
      - run: sleep 60

workflows:
  setup:
    # パラメータを指定したときだけ動くようにしといた
    when: << pipeline.parameters.config >>
    jobs:
      - setup
  testing:
    jobs:
      - runner-test
